spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/COFFEEHOUSE}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    authentication:
      jwt:
        base64-secret: WlSKedhlklTqSrR1VajEv/U46TLFKfLGqNk5d8MqfkNfyuHTuRpeu5bQCxxvvRlRk1G/F6WahwflnqKZP40KaQ==
        token-validity-in-seconds: 360000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
app:
  upload-file:
    base-path: src/Assets/

vnpay:
  tmn-code: ${VNPAY_TMN_CODE:A5029WRE}
  hash-secret: ${VNPAY_HASH_SECRET:MCTXJZ111SO42XR1CI1OO26XN1AQNAKE}
  pay-url: ${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  return-url: ${VNPAY_RETURN_URL:http://localhost:8080/orders/vnpay-return}
  frontend-return-url: ${VNPAY_FRONTEND_RETURN_URL:https://highlandscoffee-eight.vercel.app/models/UserDashBoard/index.html}
  time-zone: ${VNPAY_TIME_ZONE:Asia/Ho_Chi_Minh}
  expire-minutes: ${VNPAY_EXPIRE_MINUTES:15}